MODEL:
  BACKBONE:
    NAME: 'vgg16'
  ROI_BOX_HEAD:
    NUM_CLASSES: 2
    BOX_PREDICTOR: 'vgg16_predictor'
    POOL_TYPE: 'align'
  MODE:
    USE_STUDENT: True
    INSRANCE_ADV: True
    UPDATE_TEACHER_ITERUM: 1
    NET_MOMENTUM: 1.0
    INIT_DIS_NET: 400
    
    TRAIN_PROCESS: 'S3'
    TEST_PROCESS: 'TC'
    
    UPDATE_STUDENT_MARK: False
    UPDATE_TEACHER_MARK: True
    UPDATE_STUDENT_ITERUM: 20000
    UPDATE_TEACHER_LR: [0.92]
    UPDATE_TEACHER_INTER: [100]
    
ADV:
  LAYERS: [False, False, True]
  DIS_MODEL:
    - in_channels: 512
      func_name: 'cross_entropy'
      pool_type: 'avg'
      loss_weight: 1.0
      window_strides: [2, 2, 2, 2, 2, 2, 2]
      window_sizes: [3, 9, 15, 21, 27, 33, 37]
DATASETS:
  TRAINS: ['kitti_train']
  TARGETS: ['cityscapes_car_train']
  TESTS: ['cityscapes_car_val']
INPUT:
  TRANSFORMS_TRAIN:
    - name: 'random_flip'
    - name: 'resize'
      min_size: 600
    - name: 'normalize'
      mean: [0.5, 0.5, 0.5]
      std: [0.5, 0.5, 0.5]
      to_01: True
    - name: 'collect'
  TRANSFORMS_TEST:
    - name: 'resize'
      min_size: 600
    - name: 'normalize'
      mean: [0.5, 0.5, 0.5]
      std: [0.5, 0.5, 0.5]
      to_01: True
    - name: 'collect'
SOLVER:
  EPOCHS: 10000
  STEPS: (2000, 4000)
  LR: 1e-4
  BATCH_SIZE: 16
  GAMMA: 0.3
TEST:
  EVAL_TYPES: ['voc']

WORK_DIR: './debug/adv_vgg16_kitti_nsa_s3'
