MODEL:
  BACKBONE:
    NAME: 'vgg16'
  RPN:
    ANCHOR_SIZES: (32, 64, 128, 256, 512)
  ROI_BOX_HEAD:
    NUM_CLASSES: 9
    BOX_PREDICTOR: 'vgg16_predictor'
    POOL_TYPE: 'align'
  MODE:
    USE_STUDENT: True
    INSRANCE_ADV: True
    UPDATE_TEACHER_ITERUM: 1
    NET_MOMENTUM: 1.0
    INIT_DIS_NET: 400
    
    TRAIN_PROCESS: 'S3'
    TEST_PROCESS: 'TC'
    
    UPDATE_STUDENT_MARK: True
    UPDATE_TEACHER_MARK: True
    UPDATE_STUDENT_ITERUM: 200
    UPDATE_TEACHER_LR: [0.92,]
    UPDATE_TEACHER_INTER: [100,]
    
ADV:
  LAYERS: [False, False, True]
  DIS_MODEL:
    - in_channels: 512
      func_name: 'cross_entropy'
      pool_type: 'avg'
      loss_weight: 1.0
      window_strides: [2, 2, 2, 2, 2, 2, 2]
      window_sizes: [3, 9, 15, 21, 27, 33, 37]
DATASETS:
  TRAINS: ['cityscapes_train']
  TARGETS: ['rain_cityscapes_train']
  TESTS: ['rain_cityscapes_val']
INPUT:
  TRANSFORMS_TRAIN:
    - name: 'random_flip'
    - name: 'resize'
      min_size: 600
    - name: 'normalize'
      mean: [0.5, 0.5, 0.5]
      std: [0.5, 0.5, 0.5]
      to_01: True
    - name: 'collect'
  TRANSFORMS_TEST:
    - name: 'resize'
      min_size: 600
    - name: 'normalize'
      mean: [0.5, 0.5, 0.5]
      std: [0.5, 0.5, 0.5]
      to_01: True
    - name: 'collect'
SOLVER:
  EPOCHS: 12000
  STEPS: (8000, 10000)
  LR: 1e-4
  BATCH_SIZE: 20
  GAMMA: 0.3
TEST:
  EVAL_TYPES: ['voc']

WORK_DIR: './debug/adv_vgg16_rain_nsa_s3'
